Avoid "Text file busy" during injection
loft-sh/devpod pull request #389
Opened 2023-06-16 05:03 UTC by anguslees

Remove any existing devpod file so we don't try to write to the same inode.

Fixes "Text file busy" error:

```
16:57:57 info Inject binary
16:57:57 info done exec
16:57:58 info Done injecting binary
16:57:58 info done inject
16:57:58 info done injecting
16:57:58 info Inject Error: sh: 1: cannot create /usr/local/bin/devpod: Text file busy
16:57:58 info write |1: file already closed
```

2023-06-16 07:11 UTC, FabianKramm requested changes
@anguslees thanks a lot for the PR! Good catch, but I guess we need 2 changes:
1. Move it to before download and inject to always execute as otherwise the same issue can occur when downloading and writing to the install path
2. Make sure to ignore when `rm` fails and pipe stderr to /dev/null

2023-06-28 08:36 UTC, anguslees commented
Done.  I modified the approach to write to a tempfile and _then_ rename into place, so it will be robust to failures on the second download.   This might be over-engineering, since I don't think there's a case where the existing binary is re-executed - but I don't fully understand how/where all this gets invoked yet 😅.

2023-07-03 17:16 UTC, FabianKramm approved these changes

2023-07-03 17:53 UTC, FabianKramm commented
@anguslees looks good now, thanks a lot!

2023-07-03 17:53 UTC, merged