feat: Ignore gitignored files when uploading
loft-sh/devpod pull request #778
Opened 2023-10-25 13:55 UTC by Aunali321

Completes #677

2023-10-26 05:38 UTC, pascalbreuninger commented
Hi @Aunali321, thanks for the PR. 
As mentioned in the issue, not uploading `gitignore`d files might be unexpected for some users whilst desired by others. Could you add an option to configure this please? I.e. `devpod up $REPO --gitignore`
If you pass it through the `CLIOptions` struct it will be available in the agent `up` command, and you can pipe it into the grpc client from there

2023-10-30 11:49 UTC, Aunali321 commented
@pascalbreuninger can you review again? Thanks

2023-10-31 06:58 UTC, pascalbreuninger commented
@Aunali321 I think you'll have to vendor the dependencies and fix the golangci-lint errors, currently no pipeline workd

2023-10-31 07:19 UTC, pascalbreuninger requested changes
Couple of changes that need to be made, I think you'll need to fix your build and vendor dependencies as well (as mentioned above)

2023-10-31 07:19 UTC, pascalbreuninger commented on cmd/up.go
> +	up := &upCmd{
Not sure where this is being used, is this a leftover?

2023-10-31 07:19 UTC, pascalbreuninger commented on cmd/up.go
> +	gitIgnore bool
This should be a flag eventually, right? Could you add it to the `upCmd` flags in line 119 and following please?

2023-10-31 07:19 UTC, pascalbreuninger commented on pkg/agent/tunnelserver/stream.go
> +		gitIgnoreEnabled: gitIgnoreEnabled,
this field isn't on the struct

2023-10-31 07:19 UTC, pascalbreuninger commented on pkg/agent/tunnelserver/stream.go
> +		gitIgnore = gitignore.NewGitIgnore() // Use an empty IgnoreParser object if parsing fails
Apparently the package doesn't have this function, what's an alternative here?

2023-10-31 07:19 UTC, pascalbreuninger commented on pkg/agent/tunnelserver/stream.go
> +		if !s.gitIgnore.Match(relPath, info.IsDir()) || !s.gitIgnoreEnabled { // Check if gitIgnoreEnabled is true
Is there a way of doing this check before we start walking the filesystem? Seems like a lot of unnecessary work if we don't want to ignore `.gitignore`

2023-11-09 09:27 UTC, Aunali321 commented
Sorry i don't have enough Golang language to complete this PR.

2023-11-09 09:28 UTC, Aunali321 commented
Sorry i don't have enough Golang language to complete this PR.

2023-11-22 09:01 UTC, closed without merging

2023-11-22 09:13 UTC, pascalbreuninger commented
Hey @Aunali321, we can still work on that PR if you're interested

2023-11-24 12:40 UTC, Aunali321 commented
As i said i have 0 knowledge about Golang. i gave it a shot because i had time (which i don't anymore) but thanks!